// AUTO-GENERATED by scratchpad/pinbuild/generate_pins.mjs — do not edit by hand.
// One bundled pin image per taxonomy emoji (Twemoji on a white/purple disc).
// Keyed by the exact emoji string emojiForItem() returns, referenced from the
// map symbol layer via iconImage. Twemoji is CC-BY 4.0.
import type { ImageSourcePropType } from "react-native";

export const MAP_PIN_IMAGES: Record<string, ImageSourcePropType> = {
  "🍺": require("../../assets/mappins/1f37a.png"),
  "🍸": require("../../assets/mappins/1f378.png"),
  "🍷": require("../../assets/mappins/1f377.png"),
  "🍽️": require("../../assets/mappins/1f37d.png"),
  "☕": require("../../assets/mappins/2615.png"),
  "🥐": require("../../assets/mappins/1f950.png"),
  "🍦": require("../../assets/mappins/1f366.png"),
  "🦪": require("../../assets/mappins/1f9aa.png"),
  "🪩": require("../../assets/mappins/1faa9.png"),
  "🎭": require("../../assets/mappins/1f3ad.png"),
  "🖼️": require("../../assets/mappins/1f5bc.png"),
  "🏛️": require("../../assets/mappins/1f3db.png"),
  "🎬": require("../../assets/mappins/1f3ac.png"),
  "📚": require("../../assets/mappins/1f4da.png"),
  "📖": require("../../assets/mappins/1f4d6.png"),
  "🎵": require("../../assets/mappins/1f3b5.png"),
  "💪": require("../../assets/mappins/1f4aa.png"),
  "🧘": require("../../assets/mappins/1f9d8.png"),
  "💆": require("../../assets/mappins/1f486.png"),
  "💅": require("../../assets/mappins/1f485.png"),
  "🏅": require("../../assets/mappins/1f3c5.png"),
  "⚽": require("../../assets/mappins/26bd.png"),
  "🎳": require("../../assets/mappins/1f3b3.png"),
  "⛳": require("../../assets/mappins/26f3.png"),
  "🎡": require("../../assets/mappins/1f3a1.png"),
  "🏊": require("../../assets/mappins/1f3ca.png"),
  "🌳": require("../../assets/mappins/1f333.png"),
  "🥾": require("../../assets/mappins/1f97e.png"),
  "🏞️": require("../../assets/mappins/1f3de.png"),
  "🏕️": require("../../assets/mappins/1f3d5.png"),
  "⛵": require("../../assets/mappins/26f5.png"),
  "🏖️": require("../../assets/mappins/1f3d6.png"),
  "🌾": require("../../assets/mappins/1f33e.png"),
  "🧺": require("../../assets/mappins/1f9fa.png"),
  "🌷": require("../../assets/mappins/1f337.png"),
  "🗽": require("../../assets/mappins/1f5fd.png"),
  "🛍️": require("../../assets/mappins/1f6cd.png"),
  "🎪": require("../../assets/mappins/1f3aa.png"),
  "📅": require("../../assets/mappins/1f4c5.png"),
  "📍": require("../../assets/mappins/1f4cd.png"),
};

export const MAP_PIN_EMOJIS: string[] = Object.keys(MAP_PIN_IMAGES);
