// Generate .env.cloud.local (gitignored) — the env block to paste into the
// claude.ai/code Cloud Environment for Slack/mobile parity. STAGING-pointed by
// design (bare SUPABASE_* = staging), prod write creds deliberately excluded.
// Reads your local .env.local / .env.staging / .env. Prints ONLY key names +
// whether each is filled — never values. Re-run after rotating any key.
import fs from "node:fs";

function parse(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf("=");
    if (i < 0) continue;
    out[line.slice(0, i).trim()] = line.slice(i + 1).replace(/\r$/, "");
  }
  return out;
}

const local = parse(".env.local");
const stg = parse(".env.staging");
const base = parse(".env");
const v = (...keys) => { for (const k of keys) { const s = local[k] ?? stg[k] ?? base[k]; if (s && s.trim()) return s; } return ""; };

// name -> source value (staging-pointed for the bare SUPABASE_* + EXPO_PUBLIC_*)
const spec = {
  // Supabase (staging-pointed)
  SUPABASE_URL: v("SUPABASE_STAGING_URL"),
  SUPABASE_ANON_KEY: v("SUPABASE_STAGING_ANON_KEY"),
  SUPABASE_SERVICE_ROLE_KEY: v("SUPABASE_STAGING_SERVICE_ROLE_KEY"),
  SUPABASE_ACCESS_TOKEN: v("SUPABASE_ACCESS_TOKEN"),
  SUPABASE_STAGING_URL: v("SUPABASE_STAGING_URL"),
  SUPABASE_STAGING_ANON_KEY: v("SUPABASE_STAGING_ANON_KEY"),
  SUPABASE_STAGING_SERVICE_ROLE_KEY: v("SUPABASE_STAGING_SERVICE_ROLE_KEY"),
  SUPABASE_STAGING_DB_PASSWORD: v("SUPABASE_STAGING_DB_PASSWORD"),
  SUPABASE_STAGING_PROJECT_ID: v("SUPABASE_STAGING_PROJECT_ID"),
  STAGING_SUPABASE_URL: v("SUPABASE_STAGING_URL", "STAGING_SUPABASE_URL"),
  STAGING_SERVICE_ROLE_KEY: v("SUPABASE_STAGING_SERVICE_ROLE_KEY", "STAGING_SERVICE_ROLE_KEY"),
  // Expo / client (staging for cloud)
  EXPO_TOKEN: v("EXPO_TOKEN"),
  EXPO_PUBLIC_SUPABASE_URL: v("SUPABASE_STAGING_URL"),
  EXPO_PUBLIC_SUPABASE_ANON_KEY: v("SUPABASE_STAGING_ANON_KEY"),
  EXPO_PUBLIC_SENTRY_DSN: v("EXPO_PUBLIC_SENTRY_DSN"),
  EXPO_PUBLIC_PHONE_HASH_SALT: v("EXPO_PUBLIC_PHONE_HASH_SALT"),
  // Sentry
  SENTRY_DSN_EDGE: v("SENTRY_DSN_EDGE"),
  SENTRY_AUTH_TOKEN: v("SENTRY_AUTH_TOKEN"),
  SENTRY_ORG_AUTH_TOKEN: v("SENTRY_ORG_AUTH_TOKEN"),
  // Third-party APIs
  ANTHROPIC_API_KEY: v("ANTHROPIC_API_KEY"),
  GOOGLE_PLACES_API_KEY: v("GOOGLE_PLACES_API_KEY"),
  PREDICTHQ_API_KEY: v("PREDICTHQ_API_KEY"),
  TICKETMASTER_API_KEY: v("TICKETMASTER_API_KEY"),
  RESEND_API_KEY: v("RESEND_API_KEY"),
  // Test accounts (USER_A/B not in .env.local — fill from GitHub Secrets)
  USER_A_EMAIL: v("USER_A_EMAIL"),
  USER_A_PASSWORD: v("USER_A_PASSWORD"),
  USER_B_EMAIL: v("USER_B_EMAIL"),
  USER_B_PASSWORD: v("USER_B_PASSWORD"),
  ADMIN_EMAIL: v("ADMIN_EMAIL"),
  ADMIN_PASSWORD: v("ADMIN_PASSWORD"),
  NORMAL_EMAIL: v("NORMAL_EMAIL"),
  NORMAL_PASSWORD: v("NORMAL_PASSWORD"),
  REVIEW_EMAIL: v("REVIEW_EMAIL"),
  REVIEW_PASSWORD: v("REVIEW_PASSWORD"),
  // GitHub PAT (optional; push/PR in cloud uses the GitHub App)
  GITHUB_TOKEN: v("GITHUB_TOKEN"),
};

const header = `# Cloud Environment for claude.ai/code — paste into "Environment variables".
# Generated by scripts/gen_cloud_env.mjs from your local env. STAGING-pointed.
# Prod write creds intentionally omitted (prod = gated pipeline). Do not commit.
`;
const body = Object.entries(spec).map(([k, val]) => `${k}=${val}`).join("\n");
fs.writeFileSync(".env.cloud.local", header + body + "\n");

const blanks = Object.entries(spec).filter(([, val]) => !val).map(([k]) => k);
console.log("Wrote .env.cloud.local with", Object.keys(spec).length, "keys.");
console.log("Filled:", Object.keys(spec).length - blanks.length, "| Blank (fill manually):", blanks.length);
if (blanks.length) console.log("  -> " + blanks.join(", "));
